#version 450

layout(local_size_x = 8, local_size_y = 4) in;
layout(rgba16f, set = 0, binding = 0) uniform writeonly image2D colorBuffer;

void main() {
	ivec2 pixelPosition = ivec2(gl_GlobalInvocationID.xy);
	ivec2 screenSize = imageSize(colorBuffer);

	if (pixelPosition.x >= screenSize.x || pixelPosition.y >= screenSize.y) {
		return;
	}

	imageStore(colorBuffer, pixelPosition, vec4(0.001 * pixelPosition.x, 0.0, 0.001 * pixelPosition.y, 1.0));
}